---
title: "Plot CTA1 comp ASR"
output: html_document
date: "2023-08-05"
---
# Import data
```{r}
library(tidyverse)
raw <- read.table("/space/htang5/Downloads/Thesis/Chapter 3-ASR Secondary/Input/Ch3-DiverseROS.tsv", sep="\t", header=TRUE)
 summary(raw)
```

```{r}
library(dplyr)
tmp <-  raw %>%
  mutate(
    scaled = Count * Dilutions * 1e-2
  ) %>% 
  # remove uninformative columns. only one H2O2 conc used for each species
  select(-Len_1, -Len_2)
dat.f3 <- tmp %>% 
  # group by primary to calculate r (MO/MM) or r' (PO/PM)
  separate(Group, into = c("Primary", "Secondary"), sep = 1) %>% 
  group_by(Date, Strain, Primary) %>% 
  mutate(scaled_M = scaled[Secondary == "M"],
         r = num(scaled / scaled[Secondary == "M"], digits = 3)) %>% 
   dplyr::filter(Secondary != "M") %>%
  #pivot_wider(id_cols = c(Date, Strain, Concentration, Oxidant), 
              #names_from = Primary, values_from = r, names_prefix = "r") %>% 
  #mutate(ASR_score = rP / rM) %>%
mutate(Label = paste(Oxidant, Concentration, sep = "_"))
print(dat.f3)
#write_tsv(dat.f3, file = "/space/htang5/Downloads/Thesis/Chapter 3-ASR Secondary/Output/ROSASR-Calculated.tsv")
```
### Plot (all data)
```{r}
library(ggplot2)
require(tidyverse)
require(cowplot)
require(broom)
dat.f3 %>% 
  mutate( Primary = factor(Primary, levels = c("M", "P"), 
                     labels = c("Mock", "-Pi")),
          Oxidant = factor(Oxidant, levels = c("tBOOH", "MSB", "H2O2"), 
                     labels = c("t-BuOOH", "MSB", "H2O2")),
  ) %>%
  dplyr::filter(Label %in% c("tBOOH_2mM", "MSB_400 mM", "H2O2_60 mM")) %>% 
  ggplot(aes(x = Primary, y = r)) + 
  geom_point(aes(shape = Primary), stroke = 1, size = 2, 
             position = position_dodge(0.9)) +
  stat_summary(aes(group = Primary), position = position_dodge(0.9),
               fun = mean, fun.max = mean, fun.min = mean,
               geom = "crossbar", color = "red", width = 0.5) +
  facet_wrap(~ Oxidant, nrow = 1, scales = "free_x") +
  scale_shape_manual(values = c("Mock" = 1, "-Pi" = 16)) +
  scale_y_continuous(limits = c(0, 0.4), labels = scales::percent) +
  xlab("Primary stress (45 min)") + ylab("% survival") +
  panel_border(color = "black", size = 1.5) +
  theme(axis.line = element_blank(),
        axis.title.x = element_blank(), 
        strip.background = element_blank(),
        panel.background = element_blank(),# Remove strip background
        axis.text.x = element_text(size = 20, face = "bold", color = "black"),  # Adjust size and face (bold)
        axis.text.y = element_text(size = 20, face = "bold", color = "black"),
        axis.title.y = element_text(size = 20, face = "bold")
  )+ 
  theme(strip.text = element_text(size = 20, face = "bold"))
#ggsave("../Output/20240313-OxidantASR-Plot.png")
```

> t-BuOOH Basal survival plot

```{r}
library(ggplot2)
require(tidyverse)
require(cowplot)
require(broom)
dat.f3 %>% 
  mutate( Primary = factor(Primary, levels = c("M", "P"), 
                     labels = c("Mock", "-Pi")),
          Oxidant = factor(Oxidant, levels = c("tBOOH", "MSB", "H2O2"), 
                     labels = c("t-BuOOH", "MSB", "H2O2")),
  ) %>%
  dplyr::filter(Label %in% c("tBOOH_1 mM", "tBOOH_1.5 mM", "tBOOH_2mM")) %>% 
  ggplot(aes(x = Primary, y = r)) + 
  geom_point(aes(shape = Primary), stroke = 1, size = 2, 
             position = position_dodge(0.9)) +
  stat_summary(aes(group = Primary), position = position_dodge(0.9),
               fun = mean, fun.max = mean, fun.min = mean,
               geom = "crossbar", color = "red", width = 0.5) +
  facet_wrap(~ Oxidant + Concentration, nrow = 1, scales = "free_x") +
  scale_shape_manual(values = c("Mock" = 1, "-Pi" = 16)) +
  scale_y_continuous(limits = c(0, 0.4), labels = scales::percent) +
  xlab("Primary stress (45 min)") + ylab("% survival") +
  panel_border(color = "black", size = 1.5) +
  theme(axis.line = element_blank(),
        axis.title.x = element_blank(), 
        strip.background = element_blank(),
        panel.background = element_blank(),# Remove strip background
        axis.text.x = element_text(size = 20, face = "bold", color = "black"),  # Adjust size and face (bold)
        axis.text.y = element_text(size = 20, face = "bold", color = "black"),
        axis.title.y = element_text(size = 20, face = "bold")
  )+ 
  theme(strip.text = element_text(size = 20, face = "bold"))
ggsave("../Output/20240517-t-BuOOH-Basal-Plot.png")
```
> MSB Basal survival plot

```{r}
library(ggplot2)
require(tidyverse)
require(cowplot)
require(broom)
dat.f3 %>% 
  mutate( Primary = factor(Primary, levels = c("M", "P"), 
                     labels = c("Mock", "-Pi")),
          Oxidant = factor(Oxidant, levels = c("tBOOH", "MSB", "H2O2"), 
                     labels = c("t-BuOOH", "MSB", "H2O2")),
  ) %>%
  dplyr::filter(Label %in% c("MSB_300 mM", "MSB_350 mM", "MSB_400 mM")) %>% 
  ggplot(aes(x = Primary, y = r)) + 
  geom_point(aes(shape = Primary), stroke = 1, size = 2, 
             position = position_dodge(0.9)) +
  stat_summary(aes(group = Primary), position = position_dodge(0.9),
               fun = mean, fun.max = mean, fun.min = mean,
               geom = "crossbar", color = "red", width = 0.5) +
  facet_wrap(~ Oxidant + Concentration, nrow = 1, scales = "free_x") +
  scale_shape_manual(values = c("Mock" = 1, "-Pi" = 16)) +
  scale_y_continuous(limits = c(0, 0.4), labels = scales::percent) +
  xlab("Primary stress (45 min)") + ylab("% survival") +
  panel_border(color = "black", size = 1.5) +
  theme(axis.line = element_blank(),
        axis.title.x = element_blank(), 
        strip.background = element_blank(),
        panel.background = element_blank(),# Remove strip background
        axis.text.x = element_text(size = 20, face = "bold", color = "black"),  # Adjust size and face (bold)
        axis.text.y = element_text(size = 20, face = "bold", color = "black"),
        axis.title.y = element_text(size = 20, face = "bold")
  )+ 
  theme(strip.text = element_text(size = 20, face = "bold"))
ggsave("../Output/20240517-MSB-Basal-Plot.png")
```

# Statistical Tests#

```{r}
tmp2 <- dat.f3 %>% 
  dplyr::filter(Label %in% c("tBOOH_2mM"))
x <- Hmisc::smean.cl.boot(tmp2$ASR_score)
sprintf("ASR_score mean = %.2f, 95%% CI by bootstrap = [%.2f, %.2f]", x[1], x[2], x[3])

with(tmp2, t.test(as.numeric(rP), as.numeric(rM), paired = TRUE, alternative = "g"))

with(tmp2, wilcox.test(rP, rM, paired = TRUE, alternative = "g"))
```

```{r}
tmp2 <- dat.f3 %>% 
  dplyr::filter(Label %in% c("MSB_400 mM"))
x <- Hmisc::smean.cl.boot(tmp2$ASR_score)
sprintf("ASR_score mean = %.2f, 95%% CI by bootstrap = [%.2f, %.2f]", x[1], x[2], x[3])

with(tmp2, t.test(as.numeric(rP), as.numeric(rM), paired = TRUE, alternative = "g"))

with(tmp2, wilcox.test(rP, rM, paired = TRUE, alternative = "g"))
```


```{r}
tmp2 <- dat.f3 %>% 
  dplyr::filter(Label %in% c("H2O2_60 mM"))
x <- Hmisc::smean.cl.boot(tmp2$ASR_score)
sprintf("ASR_score mean = %.2f, 95%% CI by bootstrap = [%.2f, %.2f]", x[1], x[2], x[3])

with(tmp2, t.test(as.numeric(rP), as.numeric(rM), paired = TRUE, alternative = "g"))

with(tmp2, wilcox.test(rP, rM, paired = TRUE, alternative = "g"))
```

